import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import oreoSundae from "/public/oreoSundae.jpg";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <nav className={styles.nav}>
        <div className={styles.navMenu}>Menu</div>
        <div className={styles.navLogo}>Esmeraldas</div>
        <div className={styles.navContact}>Contact</div>
      </nav> */}
      <section className={styles.hero}>
        <div className={styles.introContainer}>
          <p>ESMERALDAS</p>
        </div>
        <div className={styles.imageContainer}>
          <img
            className={styles.image}
            src="https://images.unsplash.com/photo-1559620192-032c4bc4674e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=729&q=80"
            alt="A deliscious raspberry cake, you wouldnt believe how good it is."
          />
          {/* <Image className={styles.watch} src={"/cake.jpg"} alt="cake" fill /> */}
        </div>
      </section>
      {/* <section className={styles.hero}>
        <div className={styles.imageContainer}>
          <img
            className={styles.image}
            src="https://images.unsplash.com/photo-1602419260650-697189b3d7db?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1032&q=80"
          ></img>
        </div>
      </section> */}
      <main className={styles.main}>
        <section className={styles.cakeInfo}>
          <h1>
            Welcome to <span>CAKE HEAVEN</span>
          </h1>
          <h2>Voted Best Cakes in SoCal, 2022</h2>
        </section>
        <section className={styles.favorites}>
          <h3 className={styles.favHeader}>TRENDING FAVES</h3>
          <div className={styles.cakes}>
            <div className={styles.cakeBox}>
              <img
                className={styles.image}
                src="https://images.unsplash.com/photo-1567171466295-4afa63d45416?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80"
                alt="Blueberry CheeseCake"
              />
            </div>
            <div className={styles.cakeBox}>
              <h3>Blueberry CheeseCake</h3>
              <p>
                Tart and creamy perfection, a slice straight from your dreams.
              </p>
            </div>
          </div>
          <div className={styles.cakes}>
            <div className={styles.cakeBox}>
              <h3>Caramel Cookie</h3>
              <p>
                A wonderful combination of caramel and sea salt, with a fresh
                baked cookie on top.
              </p>
            </div>
            <div className={styles.cakeBox}>
              <img
                className={styles.image}
                src="https://images.unsplash.com/photo-1616150679978-02fbd7b42120?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80"
                alt="Caramel Cookie Cake"
              />
            </div>
          </div>
          <div className={styles.cakes}>
            <div className={styles.cakeBox}>
              <img
                className={styles.image}
                src="https://images.unsplash.com/photo-1624000961428-eeece184988b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80"
                alt="Orange Zest Cake"
              />
            </div>
            <div className={styles.cakeBox}>
              <h3>Orange Zest 10 Layer </h3>
              <p>10 Layers of Creme, orange zest, and love.</p>
            </div>
          </div>
          <div className={styles.cakes}>
            <div className={styles.cakeBox}>
              <h3>Raspberry Tres Leches</h3>
              <p>
                Fresh Raspberries on top of a creamy tres leches cake with a
                final cinnamon chocolate layer.
              </p>
            </div>
            <div className={styles.cakeBox}>
              <img
                className={styles.image}
                src="https://images.unsplash.com/photo-1619985632461-f33748ef8f3e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1075&q=80"
                alt="Tres Leches Cake"
              />
            </div>
          </div>
        </section>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
